### ISSUE TITLE
Buy a motherfucking couch

### ISSUE THREAD

**Issue by ELLIOTTCABLE** [ELLIOTTCABLE/270#18]
Seriously, buy a motherfucking couch

**Comment by chelseapeterson** [comment]
Can I "like" this? Is that a thing I can do?

**Comment by ELLIOTTCABLE** [comment]
@chelseapeterson generally, the convention is to use a thumbs-up icon. That's achieved by typing `:+1:` (icons' names come between colons, like `:smile:`.)

Instead of that, the secondary convention, is to post an approving `.gif` image. Not even kidding. #LOLGitHub

**Comment by ELLIOTTCABLE** [comment]
After hanging out at Room & Board for a while, and ass-testing a bunch of couches, I think I love this one the most:

[![Anson Leather Sofa by Room & Board](https://f.cloud.github.com/assets/200/1658849/bc3e3adc-5b99-11e3-96be-787e3f6a3d2b.jpeg)](http://www.roomandboard.com/rnb/customproduct/upholstery/detail.do?articleNumber=10005330&customConfiguration=RB_STYLE_CHOICE%7C02%7CA_LEATHER_NAMES%7CF05%7CLEATHER_COLORWAYS%7CLC03%7CRB_A_WOOD_FOOT_FINISH%7CCC)
